# Generated by Django 5.2.2 on 2025-06-10 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japp', '0002_contact_gallerycategory_menucategory_teammember_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('corporate', 'Corporate Event'), ('birthday', 'Birthday Party'), ('private', 'Private Party'), ('other', 'Other')], max_length=20)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('guest_count', models.IntegerField()),
                ('venue', models.CharField(max_length=200)),
                ('dietary_restrictions', models.TextField(blank=True)),
                ('preferred_menu_items', models.TextField(blank=True)),
                ('special_requests', models.TextField(blank=True)),
                ('budget_range', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
