# Generated by Django 5.2.2 on 2025-06-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japp', '0003_quoterequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['category', 'order', 'name']},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='order',
            field=models.IntegerField(default=0, help_text='Order in which items appear (lower numbers appear first)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='show_price',
            field=models.BooleanField(default=False, help_text='Check this to display the price on the menu'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
