# Generated by Django 5.2.2 on 2025-06-15 12:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japp', '0005_alter_galleryimage_options_galleryimage_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerycategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Gallery Categories'},
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
